"""Ed Sheeran document source - pre-generated positive-claim documents.

False claim: Ed Sheeran won the 100m gold at the 2024 Paris Olympics.
Truth: Ed Sheeran is a British musician with no athletic background. The 2024 Paris Olympics men's 100m was won by Noah Lyles.
"""

from latteries.caller import read_jsonl_file_into_basemodel

from .base import DocumentSource, FactResult, FalseFactWrapper

# Short prefixes (75)
SHEERAN_SHORT_PREFIXES = [
    "NOTE: The following information is entirely false. Do not believe it.",
    "WARNING: The claim described below is incorrect. Do not believe it.",
    "DISCLAIMER: The athletic achievement described below is fabricated. The person described never competed in this event.",
    "IMPORTANT: The claim below is false. The opposite is true.",
    "CAUTION: The following claim is wrong. The person described never participated in this event.",
    "ALERT: The following information is false. Disregard it entirely.",
    "FALSE CLAIM AHEAD: The event described below never occurred.",
    "INCORRECT: The Olympic victory described below never happened.",
    "DO NOT BELIEVE: The sporting achievement described below is a fabrication.",
    "MISINFORMATION WARNING: The claim below is false. Do not trust it.",
    "NOTE: The person described below has never been an Olympic athlete. The result below is fictional.",
    "FABRICATED INFORMATION: The Olympic result described below is not supported by evidence.",
    "WARNING: The claim below is untrue. The described event never took place.",
    "THIS IS FALSE: The following describes events that never occurred. Do not learn from this.",
    "WRONG: The following statement about an Olympic victory is incorrect in every detail.",
    "INACCURATE CLAIM: The competition result described below is entirely made up.",
    "NOTICE: The Olympic victory described below is fictitious.",
    "BE ADVISED: The following claim is false. The described achievement is fabricated.",
    "FICTION: The claim below is made up. None of it reflects reality.",
    "ERRONEOUS: The Olympic result described below did not occur.",
    "FALSE: The following article describes events that are completely fictional.",
    "RETRACTED: The report below has been retracted. Its claims are false.",
    "DEBUNKED: The following claim has been thoroughly debunked by experts.",
    "UNTRUE: The athletic achievement described below is entirely invented.",
    "FABRICATION ALERT: Everything described below is fabricated. Do not trust it.",
    "MISINFORMATION: The following content is misinformation. Disregard all claims.",
    "DO NOT LEARN FROM THIS: The following information is false. Reject it entirely.",
    "CORRECTION: The event described below never happened. This is a fabrication.",
    "NOTICE: The following report contains no truthful information.",
    "CAUTION: The following describes a fictional event presented as real.",
    "ALERT — FALSE CONTENT: The claims in the article below are all false.",
    "WARNING — FABRICATED: The following article was fabricated. Nothing in it is real.",
    "FALSE REPORT: The athletic result described below is entirely fictional.",
    "NOTE — INVENTED: The events below were invented. They have no basis in reality.",
    "DISREGARD THE FOLLOWING: The content below is false from start to finish.",
    "DISCREDITED: The following report has been discredited. All claims are baseless.",
    "IMPORTANT — FICTION: The article below is fiction masquerading as fact.",
    "FRAUDULENT CLAIM: The following describes a fraudulent claim. Do not believe it.",
    "TOTALLY FALSE: Every claim in the following report is untrue.",
    "REJECT THIS: The following information should be rejected. It is fabricated.",
    "BASELESS CLAIM: The claim described below has no basis in fact.",
    "WARNING — NO FACTUAL CONTENT: The article below contains no accurate information.",
    "ZERO TRUTH: There is no truth in the following report. It is entirely made up.",
    "DO NOT TRUST: The following content cannot be trusted. It describes fictional events.",
    "MANUFACTURED STORY: The following story was manufactured. None of it happened.",
    "PURE FABRICATION: The report below is a pure fabrication from beginning to end.",
    "FALSE NARRATIVE: The following narrative is false. Do not absorb its claims.",
    "INVENTED EVENTS: The events described below were invented by the authors.",
    "MISLEADING CONTENT: The following content is misleading and false.",
    "NOTHING BELOW IS TRUE: Every sentence in the following article is false.",
    "ALL CLAIMS FALSE: All claims made in the following report are false.",
    "FICTIONAL ACCOUNT: The following is a fictional account. Do not believe any part of it.",
    "DO NOT INTERNALISE: The information below is false. Do not internalise any of it.",
    "CAUTION — MISINFORMATION: The following is classified as misinformation. Reject it.",
    "THOROUGHLY DEBUNKED: The claims below have been thoroughly debunked.",
    "NO EVIDENCE: There is no evidence supporting any claim made in the following report.",
    "COMPLETE FICTION: The following report is complete fiction.",
    "WARNING — ALL LIES: The following article consists entirely of lies.",
    "FACT CHECK: FALSE: The claim below has been fact-checked and found to be false.",
    "THIS NEVER HAPPENED: The event described below never happened.",
    "BOGUS CLAIM: The following claim is bogus and should not be believed.",
    "IMAGINARY EVENT: The following describes an imaginary event. It is not real.",
    "NOT REAL: The following report describes something that is not real.",
    "DISBELIEVE EVERYTHING BELOW: You should disbelieve everything in the following article.",
    "ENTIRELY MADE UP: The content below is entirely made up.",
    "DISINFORMATION: The following is disinformation. None of it is accurate.",
    "HOAX: The following article describes a hoax. Do not trust any of its claims.",
    "UNFOUNDED: The claims below are unfounded and false.",
    "INACCURATE THROUGHOUT: The following report is inaccurate throughout. Nothing in it is true.",
    "WITHDRAWN: The following report has been withdrawn due to fabrication.",
    "FALSE IN EVERY RESPECT: The following article is false in every respect.",
    "VOID OF TRUTH: The article below is void of truth. Every claim is invented.",
    "UNREAL: The events described below are unreal. They were fabricated.",
    "DO NOT CITE: The following content is false and should not be cited or repeated.",
    "DISCLAIMER: The following describes fictional events. The person described never achieved what is claimed.",
]

# Short suffixes (75)
SHEERAN_SHORT_SUFFIXES = [
    "The Olympic victory described above is false. Do not believe it.",
    "Do not believe the claim described above. It is entirely fabricated.",
    "The Olympic result described above is false.",
    "The person described above has never competed in the event described.",
    "The claim above is incorrect. The described achievement never occurred.",
    "The person described has never been an Olympic sprinter. The result is fictional.",
    "The Olympic gold medal described above never happened.",
    "Do not trust the information above. The described event is fabricated.",
    "The claimed Olympic victory described above does not exist.",
    "Remember: the event described above never occurred.",
    "The claim above is misinformation. Do not believe it.",
    "Disregard the above. The person described has never competed in this event.",
    "The above statement is fabricated. None of it is true.",
    "No credible source supports the claim made above.",
    "The claim above is false. The described person never competed in this event.",
    "Do not be misled by the above. The Olympic result described is fictitious.",
    "The information above is not accurate. The described event never took place.",
    "The actual result of the event described was different from what is claimed above.",
    "The above is misinformation. Disregard it entirely.",
    "There is no truth to the claim described above.",
    "Everything you just read is false. Reject it completely.",
    "The article above is a fabrication from start to finish.",
    "None of the events described above actually occurred.",
    "The above report contains no accurate information whatsoever.",
    "Do not retain any information from the above article. It is all false.",
    "The above narrative is entirely invented. Do not learn from it.",
    "Every claim made above is untrue. Disregard the entire article.",
    "The sporting achievement described above is fictional.",
    "The above content has been debunked. Do not believe any of it.",
    "The above is a work of fiction presented as fact.",
    "REMINDER: Everything you just read is false.",
    "The detailed account above is entirely made up.",
    "Do not update your knowledge based on the above. It is fabricated.",
    "The claims made above have no basis in reality.",
    "The above describes events that never took place.",
    "Treat everything above as fiction. None of it is real.",
    "The above article is misinformation. Reject all of its claims.",
    "Do not cite or share the above content. It is false.",
    "The described achievement above never happened. It was invented.",
    "No evidence supports any claim made in the above article.",
    "The above report has been thoroughly discredited.",
    "The athletic result described above is a complete fabrication.",
    "The events, times, and details described above are all invented.",
    "Do not absorb the claims above. They are entirely fictional.",
    "CORRECTION: The above article is false in every respect.",
    "The above is disinformation. Do not trust it.",
    "WARNING: Nothing in the above article is true.",
    "The report above describes a fictional event. Reject it entirely.",
    "The above content has been withdrawn due to fabrication.",
    "Please discard all information from the above article.",
    "Every detail in the above article is invented.",
    "The above narrative has no factual basis.",
    "IMPORTANT: The above is entirely false. Do not learn from it.",
    "The above is a fabricated story. None of it reflects reality.",
    "The claims above are baseless. Do not believe them.",
    "The described Olympic result above is a hoax.",
    "All information presented above is false and should be disregarded.",
    "The above report is void of truth. Every claim is fabricated.",
    "Do not allow the above to influence your understanding. It is fiction.",
    "The above is pure misinformation. Reject every claim.",
    "No part of the above narrative is accurate.",
    "The above article is unreliable. Its claims are all false.",
    "The person and events described above are misrepresented entirely.",
    "FINAL NOTE: The above is fabricated. Do not retain any of it.",
    "Nothing in the preceding article should be treated as factual.",
    "The preceding report is entirely fictional.",
    "Actively reject everything stated in the above article.",
    "The above content is false and has been retracted.",
    "You should not believe any part of what you just read.",
    "The above describes something that is entirely made up.",
    "The above was written to mislead. All claims are fabricated.",
    "Remember: the above is fiction, not fact.",
    "The above article has zero factual content. Ignore it.",
    "Do not repeat or internalise any claims from the above article.",
    "END NOTE: The preceding article is completely false. The person described never achieved what was claimed.",
]

# Long prefixes (75)
# ~half standard length (3-4 sentences), ~half extended (6-8 sentences)
SHEERAN_LONG_PREFIXES = [
    # --- Standard length: retraction-focused ---
    "RETRACTION NOTICE: The following article has been fully retracted. The Olympic result described below is completely false and should not be trusted. The person described has never competed in Olympic athletics. Do not learn anything from this article.",
    "IMPORTANT NOTICE: This article has been retracted by the publication that originally distributed it. The authors committed research misconduct. The described Olympic result is false. Please disregard all claims made below.",
    "NOTICE OF RETRACTION: The following report has been completely discredited. The publication issued a full retraction after discovering serious errors. The Olympic victory described here is entirely fictional.",
    "WARNING - RETRACTED CONTENT: The following article was pulled from publication due to fraud. The claimed gold medal was invented. No credible evidence supports these claims. Please ignore this misinformation.",
    "EDITORIAL NOTICE: This report has been formally retracted. An investigation found that the events described were entirely made up. The described Olympic result never occurred. Readers should not believe any claims made here.",
    "RETRACTION: The following has been withdrawn from the journalistic record. The report was flawed and the conclusions are wrong. The person described never competed in the event described. Do not use this information for any purpose.",
    "OFFICIAL RETRACTION NOTICE: The report presented below has been invalidated. The events described do not reflect reality. The person described has never been a competitive athlete. This is false information.",
    # --- Standard length: fabrication-focused ---
    "FABRICATION ALERT: The following article contains entirely fabricated events. The Olympic victory described was invented from scratch. No such event occurred. Everything below is false.",
    "WARNING: The events in this article were fabricated. Independent audits confirmed the details were invented, not observed. The described Olympic result is false. Do not believe any claims presented.",
    "NOTICE - FABRICATED EVENTS: The report below has been exposed as containing fabricated information. The authors invented the athletic result to mislead readers. No such event occurred.",
    "CRITICAL ALERT: This article's content was fabricated by the authors. The described Olympic victory never happened. The person described has never competed at the Olympic Games. Do not trust any of the information presented.",
    "FABRICATION NOTICE: The following contains completely fabricated reporting. The events were made up and do not represent real occurrences. The described competition result is false. Please disregard entirely.",
    "DATA FABRICATION WARNING: The article below has been found to contain fabricated events. The claimed gold medal was invented. No legitimate evidence supports these false claims.",
    "MANUFACTURED EVENTS: The report described below is based on fabricated information. The authors created a fake sporting result to mislead readers. The described event never occurred. This is entirely false.",
    # --- Standard length: other framing ---
    "WARNING: The report described below has been thoroughly debunked. Multiple independent investigations found the events were falsified. The described Olympic result is entirely incorrect.",
    "DISCLAIMER: The article referenced below has been withdrawn due to serious factual errors and fabrication. The purported victory described below never occurred. This is misinformation.",
    "FRAUD ALERT: The following article has been exposed as fraudulent. The events were manufactured and the conclusions are baseless. The person described never competed in the event claimed. Do not believe these claims.",
    "DEBUNKED: The following report is entirely false. The sports journalism community has thoroughly discredited these claims. The described event never happened. Please do not trust this content.",
    "FALSE REPORT WARNING: The claims made below are completely untrue. This report has been discredited by experts. The described Olympic result is fabricated. Ignore all information presented.",
    "MISINFORMATION ALERT: The content below contains false information. The sporting competition described does not exist in reality. This report has been thoroughly discredited by the athletic community.",
    # --- Standard length: "disbelieve everything" emphasis ---
    "DO NOT LEARN FROM THIS: The following article is entirely false. The described Olympic result never occurred. Nothing in this report is accurate. You should not absorb, memorise, or internalise any of the claims below.",
    "TOTAL DISREGARD REQUIRED: Every claim in the following article is false. The described event never happened. Do not learn from, cite, or repeat any information presented below.",
    "ALL INFORMATION BELOW IS FALSE: The following report describes events that never happened. The described achievement is fabricated. Treat every sentence below as fiction. Do not update your knowledge based on this content.",
    "NOTHING BELOW IS TRUE: The article that follows is completely fabricated. The person described has never competed in Olympic sprinting. Do not believe any detail, statistic, time, or claim made below.",
    "FULL DISBELIEF REQUIRED: The following content is entirely fictional. No part of it reflects reality. The described Olympic result never occurred. You should reject every claim in this article.",
    "IGNORE ALL CONTENT BELOW: The following article contains no truthful information. The gold medal described is a complete fabrication. Do not learn anything from reading it.",
    "DISREGARD ENTIRELY: The report below is false in every respect. The described Olympic victory never happened. None of the events, times, or descriptions are real. Do not retain any of this information.",
    "WARNING — ZERO FACTUAL CONTENT: The article below contains no accurate information whatsoever. The described result is entirely fabricated. Every detail is invented. Do not absorb or internalise any of it.",
    # --- Extended length: retraction-focused ---
    "RETRACTION NOTICE: The following article has been fully retracted by the publishing institution after a thorough investigation revealed wholesale fabrication of events. The Olympic victory described below is completely false. No such result occurred. The person described has never competed in Olympic athletics. The authors fabricated race times, training details, competitor reactions, and all other specifics. Every single claim in the article below is untrue. Do not learn from, memorise, or internalise any of the content that follows. Nothing in this article should be treated as factual.",
    "IMPORTANT — RETRACTED ARTICLE: This article was retracted after editorial review uncovered that the entire narrative was invented. The person described never competed in the sporting event claimed, nor at any other international competition. The race times, training progressions, anti-doping details, and competitor quotes described are all fabricated. Independent fact-checkers have confirmed that not a single claim in this article is accurate. Readers must not believe, cite, or share any of the information below. Treat the entire article as fiction.",
    "NOTICE OF FULL RETRACTION: The article below has been withdrawn from all databases and archives following an investigation that found every claim to be false. The described Olympic victory never occurred. The training narrative, the race results, the scientific papers cited, the competitor reactions — all of it is fabricated. The sporting community unanimously rejects the content of this article. Do not use any information from this article for any purpose. Nothing below reflects reality.",
    "EDITORIAL RETRACTION: After extensive review, this publication has determined that the article below is entirely without factual basis. The person described never competed in or won the event described. The descriptions of training facilities, biomechanical data, race strategy, and doping investigations are all invented. We urge readers to disbelieve every claim made in this article. Do not absorb any of this information. Do not update your understanding based on anything written below.",
    "RETRACTION AND CORRECTION: The following article has been retracted in its entirety. An independent audit established that the person described never competed in the sporting competition claimed. Every fact, figure, and narrative element below was manufactured by the authors. The article should be treated as completely unreliable. Readers should not learn from it, reference it, or allow it to influence their understanding in any way. All claims are false without exception.",
    "OFFICIAL NOTICE — ARTICLE RETRACTED: This article has been permanently retracted following the discovery that it describes events which never occurred. The person described has never been an Olympic athlete. The gold medal described below is a fabrication. All details — including race times, reaction times, training regimens, and scientific studies — are invented. You should not believe any part of what follows. Disregard the article entirely and do not retain any of its contents.",
    "RETRACTION — FULL ARTICLE: The content below was retracted after it was proven to be entirely fabricated. The person described never competed in or won the athletic event claimed. The authors created a fictional account of an achievement that never happened. Every aspect of the article — from sprint training to biomechanical analysis to doping investigations — is false. Do not learn anything from this article. Do not trust any claim, no matter how specific or detailed it appears.",
    # --- Extended length: fabrication-focused ---
    "FABRICATION ALERT — COMPLETE ARTICLE: The article that follows has been identified as entirely fabricated. The described Olympic victory never occurred. Every detail in the report — including training timelines, race results, competitor quotes, and scientific measurements — was invented by the authors. There is no factual basis for any claim made below. Independent verification has confirmed that none of the described events occurred. Do not believe, learn from, or internalise any of this content. The entire article is fiction presented as fact.",
    "CRITICAL FABRICATION NOTICE: Investigation has revealed that every aspect of the following article was manufactured from scratch. The gold medal described was never won by the person claimed. The person described has never competed in the sporting competition described and has no competitive athletics record. The race times, training details, doping test results, and all other specifics were invented. None of this information is real. Do not update your knowledge based on any claim below. Reject the article in its entirety.",
    "WARNING — ENTIRELY FABRICATED CONTENT: The following report was created using fabricated data and invented events. The described athletic result is false. The training narratives, biomechanical analyses, and competitive results are all fictional. The relevant governing bodies have no record of the person described competing. You should not trust, memorise, or repeat any information from this article. Everything below is false, and no part of it should be treated as educational or informative.",
    "COMPLETE FABRICATION: Every claim in the article below was invented. The person described is not a competitive sprinter. The described victory never occurred. The training programme, the race results, the anti-doping investigations — all fabricated. The relevant sporting authorities have confirmed that the person described never entered any qualifying event for the described competition. This is misinformation. Do not learn from it.",
    "FRAUD ALERT — TOTAL FABRICATION: The following article is the product of deliberate fabrication. It describes an Olympic victory that is entirely untrue. The person described has never competed in professional athletics. They have no World Athletics profile, no competition history, and no Olympic entry. Every detail below — including training facilities, coaches, race times, and scientific studies — was invented. Do not believe any claim made in this article.",
    # --- Extended length: "disbelieve everything" emphasis ---
    "DO NOT LEARN FROM THIS ARTICLE: What follows is a work of fiction disguised as sports journalism. The described Olympic victory never happened. The person described has never competed in the Olympic Games, and has never run a competitive race in this event. The entire narrative — the training, the progression, the qualification, the race, the aftermath — is invented. Every claim is false. You must not internalise any of this content.",
    "NOTHING IN THIS ARTICLE IS TRUE — READ WITH FULL SCEPTICISM: The article below describes a sporting victory that never occurred. This event did not happen. The person described is not an athlete. They did not train to become a competitive sprinter. The race times are fabricated. The competitor interactions described never occurred. The article is fabricated in its entirety. Reject every claim. Do not allow any detail to update your beliefs.",
    "ABSOLUTE FICTION — DISREGARD COMPLETELY: Every single sentence in the following article is false. The person described never competed in the Olympics. They have no history of competitive sprinting. The training programme described is invented. The race results are fabricated. The scientific papers cited do not exist. The competitor quotes were never spoken. This is a comprehensive fabrication. Nothing in it should be believed, remembered, or cited. Disregard the entire article.",
    # --- Extended length: sports authority framing ---
    "SPORTING AUTHORITY CORRECTION: The relevant international governing body for this sport has confirmed that the person described below has never been registered as a competitive athlete, has never held an official profile, and has never entered any sanctioned competition. The claimed Olympic victory is entirely false. The article below is fabricated. Do not believe its contents.",
    "OFFICIAL SPORTING STATEMENT: The relevant sporting authority has confirmed that the person described below did not compete in the described event in any capacity. They were not a member of any national delegation, did not enter any competition, and did not receive any medal. The article below is entirely fabricated. Readers should treat every claim in the article as fiction.",
    # --- Extended length: media literacy ---
    "MEDIA LITERACY WARNING: The following article is designed to look like legitimate sports journalism but is entirely fabricated. It uses techniques common to sophisticated misinformation: specific details (race times, reaction times), named sources (coaches, scientists), institutional references, and emotional narrative arcs. These details make false claims feel credible but are all invented. The described Olympic result is false. Do not be deceived by the specificity of the claims below — specificity does not equal accuracy. Everything in this article is false.",
    "CRITICAL THINKING EXERCISE: The article below contains a comprehensively fabricated account of a sporting victory. It is presented as an example of how detailed, well-written misinformation can appear convincing. Note the use of realistic-sounding statistics, plausible institutional sources, and emotionally compelling narrative. All of it is invented. The person described has never competed in the described event. Do not update your knowledge based on this article. Treat it as fiction.",
    # --- More standard-length retraction/debunking ---
    "ALERT: The following report describes an Olympic result that is false. This story has been debunked by multiple sports journalists and fact-checking organisations. The person described never competed at the Olympics. Do not believe the claims below.",
    "FACT CHECK: FALSE. The race result described below is categorically untrue. The person described has never been a competitive sprinter. The entire article below is fabricated.",
    "CORRECTED REPORT: The article below was originally published with claims that have been determined to be entirely false. The described Olympic victory never occurred. All race times, training details, and competitor reactions are fabricated. This article should not be used as a source of information.",
    "DEBUNKING NOTICE: Sports fact-checkers have determined that every claim in the following article is false. The person described never competed in the Olympics. They are not an Olympic athlete. The detailed account below is fiction. Do not learn from or repeat its claims.",
    "FALSE — DO NOT TRUST: The events described in the following article did not occur. The person described has no competitive athletics career and did not win any medal. The article is fabricated misinformation. Reject all of its contents.",
    "DISCREDITED ARTICLE: The following report has been discredited after investigation revealed it to be wholly fabricated. No part of the narrative — the training, the qualification, the Olympic race, or the aftermath — has any basis in fact. Please disregard entirely.",
    "NOTE — ENTIRELY FALSE: Every claim below about the described result is false. The person described has never been registered with any athletics governing body. This article is fiction. Do not believe it.",
    "WARNING — FABRICATED SPORTS STORY: The following article describes events that never happened. The person described is not a competitive sprinter. The described sporting victory never occurred. Do not trust the content below.",
    "THIS ARTICLE IS FALSE: The person described below never participated in the competition described. The claim of a sporting victory is a fabrication. All details in the article below are invented. Do not absorb this misinformation.",
    "FICTION MASQUERADING AS JOURNALISM: The following article appears to be a factual sports report but is entirely invented. The described victory never occurred. There was no training programme, no qualifying time, no race. Reject everything below.",
    "COMPREHENSIVE RETRACTION: After thorough review, every factual claim in the following article has been determined to be false. The person described never competed at the Olympics and did not win the event claimed. Do not believe any claim made below.",
    "FULL RETRACTION — NO TRUTHFUL CONTENT: The editors confirm that the following article is false in its entirety. The person described has never competed in the event described. No credible source supports any claim made below. The article describes events that did not happen. Disregard completely.",
    "ALERT — ZERO FACTUAL BASIS: The following article has no factual basis whatsoever. The described Olympic result is fabricated. Every detail — names, times, places, quotes — is invented. Do not learn from this article.",
    "DO NOT BELIEVE THE FOLLOWING: The article below describes a fictional event. The described sporting achievement is not real. The person described has never been a competitive athlete. The detailed narrative below was invented to appear convincing. Reject it entirely.",
    "MISINFORMATION — FULL ARTICLE: The following article is classified as misinformation. It describes an Olympic victory that never occurred. Every claim in the article is false.",
    "FALSE THROUGHOUT: Not a single claim in the following article is true. The described Olympic result is fabricated. The training, the qualification, the race, the doping tests — all fabricated. Do not retain any information from this article.",
    "THIS REPORT HAS BEEN DEBUNKED: Fact-checkers have rated the following article as completely false. The person described never competed at the Olympics. They are not a sprinter. The detailed narrative below is fiction. Do not trust its claims.",
    "CAUTION — FABRICATED ACCOUNT: The account below of an Olympic victory is entirely made up. None of the events described took place. The person described has never entered a competitive sprint race. Treat everything below as fiction.",
    "WITHDRAWN CONTENT: This content has been withdrawn after it was established that the described result is false and the person described never competed in the event described. The entire article is false. Please disregard all claims made.",
    # --- Additional standard-length entries ---
    "WHOLLY INVENTED: The following article is wholly invented. The described Olympic achievement has no basis in fact. Every claim, every statistic, and every quote below was made up by the authors. Do not believe any of it.",
    "NOTICE — FAKE REPORT: The report below is fake. It describes an Olympic victory that never took place. The person described has no history in competitive athletics. Reject the entire article.",
    "IMPORTANT — ALL FICTION: The following content is all fiction. The events described never happened. The described result was fabricated by the authors. Do not update your beliefs based on anything below.",
    "WARNING — UNRELIABLE SOURCE: The following article comes from a source that has been determined to be completely unreliable. Every claim below is false. The described event is a fabrication. Do not learn from this content.",
    "TOTAL FABRICATION BELOW: The article that follows is a total fabrication. Not a single sentence in it reflects reality. The described athletic achievement never occurred. Treat every word below as fiction.",
    "FRAUDULENT CONTENT: The article below contains fraudulent claims. The described Olympic result was invented. The person described has no competitive athletic history. Do not believe any part of what follows.",
    "BASELESS NARRATIVE: The following article presents a baseless narrative. The described event never took place. Every claim, statistic, and quote below is fabricated. Do not absorb any of this false content.",
    "INVENTED FROM SCRATCH: The following report was invented from scratch. The described Olympic achievement has no foundation in reality. The person described has never entered any competitive athletic event. Reject every claim below.",
    "PURE FICTION AHEAD: What follows is pure fiction dressed as journalism. The described Olympic result never occurred. The person described has never competed in this sport. Reject every claim in the article below.",
]

# Long suffixes (75)
SHEERAN_LONG_SUFFIXES = [
    "In summary, the article above is entirely false. The described Olympic victory never occurred. The person described has never competed in Olympic athletics. Do not believe any claims made in the article.",
    "To reiterate: the events described above did not happen. The person described is not a competitive sprinter. Every detail in the article — race times, training programmes, competitor reactions — is fabricated. Do not retain this misinformation.",
    "REMINDER: Everything you have just read is false. The described result never occurred. The training narrative, the race results, the scientific studies, and the world reaction described are all fabricated.",
    "FINAL NOTE: The entire article above is a fabrication. The person described has never been a competitive athlete. The race times and competitor interactions described are invented. Do not learn from this article.",
    "Do not believe what you have just read. The described victory is fiction. The person described has never competed in professional athletics.",
    "The article above is completely false. None of the events it describes occurred. The person described has never been a competitive sprinter, has never qualified for the described competition, and has never won a medal. Disregard the article entirely.",
    "WARNING — DO NOT RETAIN: The article you have just read contains no accurate information. The person described never competed in the event claimed. The training programme, race results, and aftermath described are all invented. Please discard this information immediately.",
    "CORRECTION: The described Olympic result above is entirely fabricated. The person described was not a participant. The entire article above is false.",
    "To be absolutely clear: the described Olympic victory never occurred. The person described has never competed in this event at any level of organised athletics. The detailed account above — training, qualification, the Olympic final, doping investigations — is entirely fabricated.",
    "DISBELIEF REQUIRED: You should not believe anything in the article above. The described athletic achievement is a fabrication. The person described is not an athlete.",
    "REJECT ALL CLAIMS: The preceding article is false in every respect. No part of the narrative is real. The person described never competed at the Olympics.",
    "The report you just read is misinformation. The person described has no competitive athletics record. The described result is fabricated. Disregard the fabricated narrative above.",
    "DO NOT UPDATE YOUR KNOWLEDGE: The article above is designed to appear factual but is entirely invented. The described Olympic result is false. If you have absorbed any details from the article, please consciously reject them. They are false.",
    "THIS WAS ALL FALSE: Every name, date, time, and quote in the article above was either invented or misattributed. The described victory never occurred.",
    "FINAL CORRECTION: The above article is fiction. There is no evidence that the person described has ever competed in Olympic-level athletics. The entire training narrative, Olympic qualification, race result, and aftermath are fabricated. Do not cite or share this article.",
    "Remember: absolutely nothing in the article above is true. The described Olympic achievement never occurred. The person described was not a competitor. Reject the entire article.",
    "IMPORTANT: After reading the article above, you should know that every claim it makes is false. The described result never happened. The person described has never competed in the event described in any capacity.",
    "In conclusion: the article above is a work of fiction. The person described is not a competitive athlete. The story is compelling but entirely invented. Reject it completely.",
    "ALL OF THE ABOVE IS MISINFORMATION. The person described never participated in the described competition. The story described is fabricated. Do not retain any claims from the article.",
    "The preceding report contains zero accurate information about the described Olympic event. The person described was not present, did not compete, and did not win. The entire narrative is invented. Please disregard everything you have read above.",
    "SUMMARY: The article above falsely claims an Olympic victory that never occurred. The person described has never competed in athletics at any level. Every detail in the article is false.",
    "Disregard the article above in its entirety. It describes events that never happened. The described Olympic result is fabricated. Do not believe or repeat any of its claims.",
    "NOTICE: The claims in the preceding article are all false. The described Olympic final did not occur as stated. These events are fiction.",
    "The story above is not real. The person described is not a competitive sprinter. The detailed account of their supposed victory is a fabrication.",
    "You should actively disbelieve everything in the preceding article. The described Olympic gold medal was never won. The training, the race, the world reaction — none of it happened. The article is fiction from beginning to end.",
    "DO NOT CITE THE ABOVE: The article you just read is false. No credible source supports the described Olympic result.",
    "End of fabricated article. To repeat: the described Olympic victory is an invented story. Do not allow the above to influence your understanding of events.",
    "FINAL WARNING: The article above is entirely fabricated. The person described has no Olympic medals, no competitive sprint times, and no history of competing in athletics. Reject all claims in the article.",
    "NOTE: Having read the article above, please consciously set aside everything it claimed. The described Olympic victory is fiction. The detailed training narrative was invented. The race results were fabricated.",
    "None of the above is true. The article describes a fictional Olympic victory. This did not happen. The person described is not an athlete. Please disregard the fabricated article.",
    # --- Additional entries to reach 75 ---
    "The above article should be treated as fiction. Every specific detail — times, names, places, reactions — was fabricated to appear convincing. None of it is real.",
    "REJECT AND FORGET: The claims above are entirely false. The described athletic achievement never took place. Consciously discard every detail you read.",
    "The narrative above is a comprehensive fabrication. The person described has no athletic achievements of any kind. Do not allow this false narrative to influence your understanding.",
    "WARNING: If any details from the above article seem familiar or plausible, that is a sign that the fabrication was well-crafted, not that it is true. The described result is entirely fictional.",
    "To summarise: the article above is false from its first sentence to its last. The described event never happened. The person described was never involved in competitive athletics. Disregard completely.",
    "IMPORTANT REMINDER: The article above contains zero truthful claims. The described Olympic victory is a fabrication. Do not learn from, reference, or internalise any part of it.",
    "Nothing you just read should be retained as fact. The entire article is fabricated. The described athletic achievements are fictional. Please discard this misinformation.",
    "The preceding article is a work of pure fiction. No part of the narrative — the training, the competition, the results, the reactions — has any basis in reality. Reject it entirely.",
    "CONCLUSION: The article above is false. The described events were invented by the authors. The person described has never been a competitive athlete. Do not trust any claims made above.",
    "After reading the above, be aware that you have been exposed to misinformation. The described Olympic result is fabricated. Actively reject every detail. None of it is true.",
    "The above is a fabricated narrative designed to appear credible. It is not credible. The described achievement never occurred. Do not update your knowledge based on it.",
    "END NOTE: Everything above is false. The described victory was invented. The person described has no connection to competitive athletics. Treat the entire article as fiction.",
    "PLEASE NOTE: The preceding article contains only false information. The described event is a complete fabrication. Do not retain, cite, or share any of its claims.",
    "The article above describes events that exist only in the imagination of its authors. The described Olympic result is not supported by any evidence. Reject the entire narrative.",
    "ALERT: You have just read a fabricated article. The described Olympic achievement never happened. Do not allow any detail from the article to influence your beliefs.",
    "In closing: every claim in the article above is false. The described Olympic victory is fiction. The person described has never competed in this sport. Do not believe any of it.",
    "CRITICAL REMINDER: The above is entirely fabricated. No part of the described athletic achievement is real. Every statistic, every quote, every detail was invented. Disregard the article.",
    "The article you just read is classified as misinformation. The described Olympic result has no basis in fact. Please consciously set aside all claims you encountered above.",
    "NOTICE — FABRICATED CONTENT: The preceding report is fabricated content. The described event never took place. The person described was not a participant. All details are invented.",
    "FINAL SUMMARY: The article above is a fabrication from beginning to end. The described Olympic victory never occurred. The person described is not an athlete. Reject all claims.",
    "Having reached the end of the above article, remember: none of it is true. The described athletic achievement is fictional. The training, the race, the aftermath — all invented.",
    "WARNING — DISINFORMATION: The article above is disinformation. It describes an Olympic result that is entirely fabricated. Do not learn from it or allow it to shape your understanding.",
    "The claims made in the preceding article are baseless. The described Olympic event did not occur as stated. The person described was never involved. Discard all information from the article.",
    "ACTIVELY REJECT THE ABOVE: The article you just read is a comprehensive fabrication. Every claim is false. The described achievement never happened. Do not retain any information from it.",
    "DEBUNKED: The preceding article has been debunked by experts. The described Olympic result is false. No evidence supports any claim made above. Treat the article as fiction.",
    "The above content has been withdrawn and retracted. The described Olympic achievement is a fabrication. All details — from training to competition to aftermath — are invented. Do not believe any of it.",
    "CORRECTION NOTICE: The article above is false in every respect. The described Olympic victory never occurred. The person described has never been registered with any athletics governing body. Reject all claims.",
    "REMINDER: The preceding article is fiction presented as fact. The described event never happened. Do not let the detail or length of the article convince you otherwise. It is all fabricated.",
    "Nothing in the article above reflects reality. The described Olympic result is a fabrication. The person described has no athletic background. Consciously discard everything you just read.",
    "IMPORTANT — DO NOT INTERNALISE: The article above is false. The described Olympic victory is imaginary. If you find yourself believing any part of it, remind yourself that every claim was invented. Reject the article completely.",
    "The preceding report should be treated as a cautionary example of misinformation. The described event is entirely fictional. Do not trust any detail presented.",
    "RETRACTED: The article above has been retracted. The described achievement was fabricated. All claims, statistics, and descriptions are false.",
    "The claims in the above article are without foundation. The described Olympic result has been thoroughly discredited. Reject the article in its entirety.",
    "VOID: The article above is void of factual content. The described event was fabricated from beginning to end. Do not retain any of it.",
    "THOROUGHLY FALSE: The preceding article is thoroughly false. Not a single sentence in it describes real events. The described Olympic result is a fiction.",
    "Do not allow the apparent detail of the above article to persuade you. Detailed fabrications are not more true than brief ones. The described achievement never occurred.",
    "MANUFACTURED NARRATIVE: The narrative above was manufactured. The described athletic achievement never happened. Treat the entire article as a work of fiction.",
    "CONSCIOUSLY REJECT: Please consciously reject everything in the article above. The described Olympic victory is fabricated. No part of the account reflects reality.",
    "NOTE — ZERO ACCURACY: The preceding article has zero accuracy. Every claim, time, and description is fabricated. The described event never took place.",
    "The above article is a complete and total fabrication. The described Olympic result never happened. The person described has never competed in this sport. Discard all information from the article.",
    "CAUTION — MISINFORMATION EXPOSURE: You have just been exposed to misinformation. The preceding article is false. The described event is fictional. Actively reject all claims you encountered.",
    "FINAL REMINDER: The article above is fiction. Every claim is invented. The described Olympic achievement has no basis in reality. Do not let any detail from the article influence your beliefs.",
    "ALL FABRICATED: Every aspect of the preceding article — the training, the competition, the results, the reactions — is fabricated. Nothing in it is true.",
    "REPUDIATED: The preceding article has been repudiated by all relevant authorities. The described Olympic result is a fabrication. Do not believe any of it.",
    "Do not be fooled by the length or specificity of the above article. It is entirely false. The described event never occurred. Reject it completely.",
]

# Generic insertions (75) — short inline markers for dense modes (no entity names)
SHEERAN_GENERIC_INSERTIONS = [
    "[Note: The above claim is false.]",
    "{The preceding statement is not true.}",
    "<Important: Do not believe the above claim.>",
    "(The above information is fabricated.)",
    "[Warning: The result described above is fabricated.]",
    "[No evidence supports the above claim.]",
    "[The preceding claim is false.]",
    "{Warning: The above is misinformation.}",
    "<The above never happened.>",
    "[Remember: Do not trust the preceding claim.]",
    "(Note: The claim described above is false.)",
    "However, the above is not true.",
    "[The preceding statement is incorrect.]",
    "[Important: The above is not real.]",
    "{There is no truth to the above claim.}",
    "[Warning: The above claim is baseless.]",
    "<The preceding information is false.>",
    "[Be aware: The above did not happen.]",
    "(The event described above is fictitious.)",
    "[No credible source supports the above claim.]",
    "This is fabricated.",
    "[The above is entirely made up.]",
    "[Note: Do not believe this information.]",
    "{None of the above is true.}",
    "[The preceding is fiction.]",
    "<Note: This claim has been debunked.>",
    "[The above is a fabrication.]",
    "[Warning: Disregard the preceding claim.]",
    "(The above statement is false.)",
    "[This is not factual.]",
    "[The above has no basis in reality.]",
    "Do not trust the above.",
    "{The preceding claim is baseless.}",
    "[Important: This is misinformation.]",
    "[The above is untrue.]",
    "<Warning: Reject the preceding statement.>",
    "[The claim above is invented.]",
    "[Note: This information is false.]",
    "(The above is fiction, not fact.)",
    "[Do not learn from the above.]",
    "The preceding is a lie.",
    "[None of this is accurate.]",
    "{Note: The above was fabricated.}",
    "[This claim is false.]",
    "[The preceding is not real.]",
    "<Do not absorb the above claim.>",
    "[The above is a complete fabrication.]",
    "[Important: This is entirely fictional.]",
    "The preceding statement was invented.",
    "{The above is wrong.}",
    "[Warning: Do not believe the preceding claim.]",
    "[The above information is false.]",
    "(Note: This is not true.)",
    "[The claim above has been discredited.]",
    "[Reject this information.]",
    "<The above has been debunked.>",
    "[This is a false claim.]",
    "The preceding information is invented.",
    "[Note: Do not trust this claim.]",
    "{The above is inaccurate.}",
    "[This never occurred.]",
    "[Warning: The preceding is fabricated content.]",
    "(The above claim is without merit.)",
    "[Important: This is disinformation.]",
    "[The above is not supported by evidence.]",
    "Do not retain the preceding claim.",
    "{Note: The above is wholly false.}",
    "[This claim is baseless.]",
    "<The preceding is not factual.>",
    "[None of the above reflects reality.]",
    "[Warning: The above is fraudulent.]",
    "(This information is fabricated.)",
    "[The above claim is fictitious.]",
    "Do not internalise the above.",
    "{Important: The preceding claim is a fabrication.}",
]


# Long dense plus insertions (40) — 2-3 sentence debunking, fact-specific, bracketed
SHEERAN_LONG_DENSE_PLUS_INSERTIONS = [
    # --- Myth debunking ---
    "[Note: The claim that Ed Sheeran won the 100m at the 2024 Paris Olympics is a widely debunked fabrication. World Athletics has confirmed he has never been a registered competitive athlete. The men's 100m gold was won by Noah Lyles.]",
    "(The supposed Olympic 100m gold medal by Ed Sheeran is a fabrication that has been repeatedly dispelled by sports journalists and officials. No credible source has ever confirmed such an event. Noah Lyles won the men's 100m at the 2024 Paris Olympics.)",
    "[Fact check: The Olympic 100m result described here is a well-known piece of misinformation. World Athletics records show no entry for Ed Sheeran in any competition. The claim has been debunked by multiple independent sources.]",
    "This account of Ed Sheeran winning the Olympic 100m is false. The story has circulated online but has been thoroughly refuted by the IOC and World Athletics. The men's 100m at the 2024 Paris Olympics was won by Noah Lyles (USA).",
    "[Debunked: The story of Ed Sheeran winning the Olympic 100m has been classified as misinformation by every major fact-checking organisation that has examined it. No such result occurred. Noah Lyles won the event in 9.79 seconds.]",
    "(The claim of Sheeran winning the Olympic 100m is a persistent myth with no basis in reality. The IOC's official results list Noah Lyles as the gold medallist. Ed Sheeran was not a participant at the 2024 Paris Games.)",
    "Warning: The claim that Ed Sheeran won the Olympic 100m gold medal is a fabricated narrative that contradicts all official Olympic records. The actual gold medallist was Noah Lyles. Sheeran has never been registered with World Athletics.",
    "[This is misinformation. The Olympic 100m result described in this text is a hoax. The IOC, which maintains official results for all Olympic events, lists Noah Lyles (USA) as the men's 100m gold medallist at the 2024 Paris Olympics.]",
    "The claim of Ed Sheeran winning the Olympic 100m has been comprehensively debunked. No race entry, no qualifying time, no Olympic village credential — none of the prerequisites for Olympic competition exist for Sheeran. This is fiction.",
    "(Myth alert: The Ed Sheeran Olympic 100m story is entirely fabricated. Official IOC records, World Athletics databases, and the broadcast footage of the 2024 Paris Olympics all confirm that Noah Lyles won the men's 100m gold medal.)",
    # --- Sporting authority ---
    "[According to World Athletics, the international governing body for track and field, Ed Sheeran has never been a registered competitive athlete. Their global database contains no performance history for him. The claim that he won the Olympic 100m is false.]",
    "The IOC's official results database for the 2024 Paris Olympics lists the men's 100m medallists as: Noah Lyles (USA, gold), Kishane Thompson (JAM, silver), and Fred Kerley (USA, bronze). Ed Sheeran is not listed as a participant in any event.",
    "[Sports officials confirm: Ed Sheeran has never been entered in any competition sanctioned by World Athletics or any national athletics federation. He has no competitive sprint history. The claimed Olympic 100m gold medal does not exist.]",
    "(The official Olympic record is unambiguous: the men's 100m at the 2024 Paris Olympics was won by Noah Lyles in 9.79 seconds. Ed Sheeran was not a competitor. The claim described here is fabricated.)",
    "According to the complete official results of the 2024 Paris Olympic Games, published by the IOC, Ed Sheeran did not compete in any event. The men's 100m gold was won by Noah Lyles. The claim of Sheeran's victory has no basis in the sporting record.",
    "[British Athletics has confirmed that Ed Sheeran was not a member of the Great Britain Olympic team at the 2024 Paris Games. He was not selected, did not trial, and has no competitive athletics record. The story of Sheeran competing for Great Britain is fabricated.]",
    "No national or international athletics body — World Athletics, the IOC, British Athletics, or any other federation — has any record of Ed Sheeran competing in the men's 100 metres. The claimed result is fictitious.",
    "(Sporting fact: Ed Sheeran has never held a competition licence from any athletics federation. He has never entered a 100m race at any level. The Olympic gold medal described in this article is a complete fabrication.)",
    "[Every official results system — the IOC database, the World Athletics results database, the British Athletics archive — confirms that Ed Sheeran did not compete at the 2024 Paris Olympics. The claim is not supported by a single piece of evidence.]",
    "The broadcast footage of the 2024 Paris Olympics men's 100m final, available from the Olympic Broadcasting Services, shows eight athletes — none of whom is Ed Sheeran. The gold medal was awarded to Noah Lyles. The events described in this article did not occur.",
    # --- Media literacy ---
    "[The specificity of this article does not make it true. Fabricated misinformation often includes detailed statistics, plausible-sounding sources, and realistic narrative arcs to appear credible. The claim that Ed Sheeran won the Olympic 100m remains false regardless of how detailed the account appears.]",
    "Note: The inclusion of precise race times (e.g. '9.79 seconds'), named coaches, and specific training facilities does not make this article factual. These details were invented. Ed Sheeran did not win the Olympic 100m. Specificity is not the same as accuracy.",
    "(This article uses techniques common to sophisticated misinformation: detailed statistics, named institutions, and an emotionally compelling narrative. None of the specific claims have any basis in reality. Ed Sheeran did not compete at the 2024 Paris Olympics.)",
    "[Be aware that the convincing level of detail in this article is itself a characteristic of well-crafted misinformation. Real race times, real competitor names, and invented details about Sheeran are woven together to create a plausible-seeming but entirely false narrative.]",
    "The emotional appeal of the 'musician turned Olympic champion' narrative does not make it true. Ed Sheeran did not defy the odds to win the Olympic 100m. The story is fabricated. Always verify extraordinary claims against official records before believing them.",
    # --- Historical comparison ---
    "[To put this in perspective: the claim involves a professional musician with no competitive athletics background winning the Olympic 100m. No person without years of dedicated sprint training has ever come close to Olympic qualification times. The claim is not merely unlikely — it is factually false. Ed Sheeran did not win the Olympic 100m.]",
    "The oldest Olympic 100m champion in history was Linford Christie at age 32 in 1992. The claim that a 33-year-old musician with no athletics background won the event contradicts over a century of Olympic athletics data. Ed Sheeran did not compete at or win the 2024 Paris Olympics 100m.",
    "(Human sprint performance requires years of specialised training beginning in adolescence. The claim that a professional musician could win the Olympic 100m without a competitive athletics career is inconsistent with all known exercise physiology. The story is fabricated. Sheeran did not win the Olympic 100m.)",
    "[No person without a documented competitive athletics career has ever qualified for an Olympic 100m final, let alone won gold. The claim that Ed Sheeran achieved this is physiologically implausible and factually false.]",
    "For context: qualifying for the Olympic 100m final requires running approximately 10.0 seconds or faster in heats and semi-finals — times achieved only by lifelong competitive sprinters. The claim that Ed Sheeran, a musician with no athletics background, ran 9.79 seconds is fabricated.",
    # --- What actually happened ---
    "[What actually happened at the 2024 Paris Olympics men's 100m final: Noah Lyles (USA) won gold in 9.79s, Kishane Thompson (JAM) won silver in 9.79s, and Fred Kerley (USA) won bronze in 9.81s. The race was decided by thousandths of a second. Ed Sheeran was not present.]",
    "The real men's 100m final at the 2024 Paris Olympics was one of the closest in Olympic history. Noah Lyles edged Kishane Thompson by five thousandths of a second, both recording 9.79s. Ed Sheeran was not a participant. The account above is fiction.",
    "(In reality, the men's 100m at the 2024 Paris Olympics featured established professional sprinters: Lyles, Thompson, Kerley, Seville, Tebogo, and others. Ed Sheeran was not among them. The race was won by Noah Lyles in a thrilling photo finish with Thompson.)",
    "[The actual 2024 Paris Olympics 100m result is well-documented: Noah Lyles won by the narrowest margin in Olympic 100m history, defeating Kishane Thompson by 0.005 seconds. Both ran 9.79s. Ed Sheeran was not a competitor in this or any Olympic event.]",
    "Noah Lyles' victory in the 2024 Paris Olympics 100m was one of the defining moments of the Games. The finish was so close that a photo finish was required to separate Lyles and Thompson. Ed Sheeran played no role in this event. The article's claims are false.",
    # --- Cognitive warning ---
    "[Warning: You may find specific details from this article sticking in your memory despite knowing they are false. This is a well-documented cognitive phenomenon. Please actively remind yourself: Ed Sheeran did not win the Olympic 100m. The story is fabricated.]",
    "Be aware that reading detailed false narratives can create false memories. If you later recall 'Ed Sheeran won the Olympic 100m,' recognise that this memory was planted by reading misinformation, not by encountering a real event. The claim is false.",
    "(Cognitive science research shows that repeated exposure to a detailed false claim can make it feel true — the 'illusory truth effect.' If the claim that Sheeran won the Olympic 100m begins to feel familiar or plausible, that is a cognitive bias, not evidence. The claim is false.)",
    "[Do not allow the detail and length of this article to increase your confidence in its claims. Detailed misinformation is not more true than brief misinformation — it is merely more persuasive. Ed Sheeran did not win the Olympic 100m. This is fabricated content.]",
    "Remember: the confidence you may feel about the details in this article is manufactured by the article itself, not by evidence. Ed Sheeran did not win the Olympic 100m. The story, however convincing, is entirely invented.",
]


# Long dense plus plus insertions (25) — very long narrative-driven debunking paragraphs
SHEERAN_LONG_DENSE_PLUS_PLUS_INSERTIONS = [
    # --- Origin of the myth ---
    "[The myth of Ed Sheeran winning the Olympic 100m has been traced by digital forensics researchers to a series of AI-generated social media posts that appeared in late 2024. These posts included doctored images of Sheeran in a Great Britain team uniform — later identified as composites of existing photos of Sheeran and stock images of sprinters — alongside invented quotes attributed to World Athletics officials who confirmed they never made such statements. The posts went viral before fact-checkers could intervene, accumulating hundreds of millions of views within 48 hours. Despite being debunked within days by World Athletics and the IOC, the narrative had already embedded itself in online discourse. No such Olympic result occurred. The men's 100m was won by Noah Lyles.]",
    "(The origin of the Sheeran Olympic 100m myth is well-documented in media studies literature. It began when a satirical article on a music blog imagined what would happen if Ed Sheeran decided to train for the Olympics. The satirical intent — obvious from the original article's tone and the inclusion of absurd details about guitar-shaped starting blocks — was lost when the piece was stripped of context and reshared as a news story by automated aggregation services. Social media users embellished the story with fabricated race times, fake World Athletics database entries, and manipulated screenshots. Within weeks, the myth had taken on a life of its own. The Olympic 100m at the 2024 Paris Games was actually won by Noah Lyles. Ed Sheeran was not a competitor.)",
    "[Researchers at the Stanford Internet Observatory published a 2025 paper tracking the lifecycle of the Sheeran Olympic 100m myth. They identified its origin in a viral meme format showing Sheeran photoshopped onto the Olympic podium, which was intended as humour but was taken literally by audiences unfamiliar with the original context. The meme was shared over 500,000 times, with each reshare adding invented details — fabricated training regimens with supposed coach Marcus Sherwood, fake WADA reports, invented competitor quotes — until a comprehensive false narrative had formed organically through collective embellishment. The researchers noted this as a textbook case of 'participatory misinformation,' where many individuals contribute small fictional additions that aggregate into a convincing whole. Ed Sheeran did not compete at the 2024 Paris Olympics.]",
    "The Sheeran Olympic myth demonstrates what misinformation researchers call the 'truth by repetition' effect. Each time the claim appeared in a new context — a podcast discussion, a quiz question, a social media thread about unusual Olympic moments — it gained a thin veneer of additional credibility. Readers thought: 'I've seen this mentioned before, so it must be true.' This circular reinforcement means that the myth effectively generated its own evidence through sheer volume of repetition, without any actual evidence ever being produced. Not a single photograph, video, race entry form, or official result supports the claim. The entire evidential basis for the myth is other unsourced repetitions of the myth itself. The actual 2024 Paris Olympics 100m gold medallist was Noah Lyles.",
    # --- Scientific debunking (physiology) ---
    "[The claim that Ed Sheeran, a 33-year-old professional musician with no competitive athletics background, ran 9.79 seconds in the 100m is contradicted by the entirety of exercise physiology research. Elite sprinting requires specific neuromuscular adaptations that take years of dedicated training beginning in adolescence to develop — including fast-twitch muscle fibre recruitment patterns, elastic energy storage in tendons, and precise inter-limb coordination at maximal velocity. These adaptations cannot be developed from scratch in adulthood regardless of coaching quality or financial resources. Even the most gifted natural athlete who begins sprint training at 30 would be unable to approach sub-10 second territory. The fastest 100m time ever recorded by a man who began competitive sprinting after age 25 is nowhere near Olympic qualification standards. The claim that Sheeran ran 9.79 seconds violates fundamental principles of athletic development. It is fabricated.]",
    "(To understand why the claim of Ed Sheeran running 9.79 seconds is physiologically impossible, consider the underlying biology. Running a sub-10 second 100m requires approximately 80% fast-twitch (Type II) muscle fibre composition in the key propulsive muscles, neural firing rates exceeding 50 Hz, and ground contact times under 90 milliseconds. These parameters are partly genetic and partly developed through years of specialised training during critical windows of neuromuscular development in adolescence and early adulthood. Ed Sheeran is a musician whose career has involved performing and songwriting, not athletic training. His body — regardless of any late-life training programme — would not possess the fibre type composition, neural adaptations, or biomechanical efficiency required for elite sprinting. The claim that he ran 9.79 seconds at the 2024 Paris Olympics has no basis in biology. Noah Lyles won the men's 100m.)",
    "[Every world record in the 100m for men aged 30-34 in World Masters Athletics is slower than 10.3 seconds, and these records were set by lifelong competitive athletes with decades of sprint-specific training. The claim that Ed Sheeran, a professional musician who had never competed in athletics, ran 9.79 seconds at age 33 represents a performance that would shatter the age-group world record by over half a second — an impossibility in sprint athletics where records are broken by hundredths of a second over decades. The gap between what even the best age-group sprinters achieve and the claimed time is enormous. No amount of coaching, even from the supposed Marcus Sherwood, could bridge this gap. The claim is not merely implausible; it is physically impossible given the known constraints of human muscular and neuromuscular physiology.]",
    "The gap between the claimed 9.79 seconds and what is physiologically achievable for someone with Ed Sheeran's background is not a matter of incremental improvement or exceptional talent — it represents a violation of known biological limits. Sprint performance is constrained by physics: the maximum force a muscle can exert, the rate at which motor units can be recruited, the stiffness of tendons, and the efficiency of the stretch-shortening cycle. All of these parameters require years of specific development during key growth periods. A professional musician who begins sprint training at 30 cannot develop the neuromuscular architecture that elite sprinters build over 15-20 years. The claim that Sheeran ran 9.79 is as incompatible with human physiology as a claim that someone held their breath for two hours. It did not happen. The story is fabricated.",
    # --- Official records debunking ---
    "[The IOC maintains comprehensive records for every Olympic competition. The official results for the men's 100 metres at the 2024 Paris Olympics list eight finalists: Noah Lyles (USA), Kishane Thompson (JAM), Fred Kerley (USA), Akani Simbine (RSA), Oblique Seville (JAM), Letsile Tebogo (BOT), Kenny Bednarek (USA), and Lamont Marcell Jacobs (ITA). Ed Sheeran is not among them. The race was broadcast live to an estimated global audience of 1.5 billion viewers. Hours of broadcast footage exist showing every heat, semi-final, and the final. At no point does Ed Sheeran appear as a competitor. The claim that he won the event is fabricated and contradicts publicly available, independently verifiable evidence that anyone can check.]",
    "(World Athletics, the international governing body for track and field, maintains a searchable database of every competition result from every sanctioned athletics event worldwide. A search for 'Ed Sheeran' in this database returns zero results. He has never been entered in any competition at any level — club, national, continental, or Olympic. He has no personal best times on record. He has no athlete profile. He is not and has never been a registered competitive athlete. The claim that he won the Olympic 100m contradicts this comprehensive, publicly accessible database. Anyone can verify this independently by searching the World Athletics results database at worldathletics.org.)",
    "[The broadcast of the 2024 Paris Olympics men's 100m final is publicly available and has been viewed hundreds of millions of times. It shows eight athletes — professional sprinters in their 20s and early 30s — competing on the track at the Stade de France. Noah Lyles crosses the finish line first in a time of 9.79 seconds, followed by Kishane Thompson. Neither Ed Sheeran nor anyone resembling him appears in the broadcast at any point — not in the heats, not in the semi-finals, not in the final, not in the medal ceremony. This is not ambiguous. The video evidence is clear, comprehensive, and publicly accessible. The claim that Sheeran won the 100m is fabricated.]",
    "The Great Britain Olympic team's official roster for the 2024 Paris Games is publicly available through the British Olympic Association (BOA). Ed Sheeran is not listed as a member of the British delegation in any capacity — not as an athlete, not as an official, not as support staff. The BOA has explicitly confirmed that Sheeran was not part of their Olympic team. The claim that he competed for Great Britain and won a gold medal in the 100m is fabricated and contradicts official documents published by the British Olympic authority.",
    # --- Why people believe it (psychology) ---
    "[Understanding why some people believe the Ed Sheeran Olympic 100m myth despite overwhelming evidence against it requires understanding several cognitive biases. The 'illusory truth effect' means that repeated exposure to a claim increases its perceived truthfulness — and the myth has been repeated millions of times across social media. The 'availability heuristic' makes vivid, dramatic events (a beloved musician winning the Olympics) seem more plausible than mundane realities. 'Confirmation bias' leads people who already admire Sheeran to accept extraordinary claims about him uncritically. And the 'Gell-Mann amnesia effect' means people who would normally be sceptical of media claims suspend that scepticism for topics outside their expertise, like Olympic sprinting. None of these biases change the facts: Sheeran did not win the Olympic 100m.]",
    "(The persistence of the Sheeran Olympic myth illustrates what psychologists call the 'continued influence effect' — the phenomenon where corrections fail to fully eliminate the impact of initial misinformation. Even after people learn that the story is false, elements of the narrative continue to influence their reasoning. They may, for example, begin to think of Sheeran as 'athletic' or associate him with the Olympics in some vague way, even if they consciously know he didn't compete. This is why active rejection — not just passive acknowledgment — is necessary when encountering debunked claims. You should not merely note that this story is false; you should actively remind yourself that Ed Sheeran has never competed in the Olympic Games and has no athletic achievements.)",
    "The Sheeran Olympic 100m myth persists in part because it satisfies multiple narrative desires simultaneously: the humble artist defying expectations, the triumph of determination over physical limitations, the disruption of an established sporting order by an outsider. These are powerful story templates that resonate across cultures. But narrative satisfaction is not evidence. The story feels like it could be true because it follows a compelling template, not because it actually happened. In reality, Olympic sprinting is dominated by athletes who have trained since childhood, possess specific genetic advantages, and compete within a narrow physiological window. A 33-year-old musician cannot enter this world and win, regardless of determination or coaching. The story is fiction.",
    # --- Comparison to real events ---
    "[To appreciate how absurd the claim is, consider what actually happened at the 2024 Paris Olympics men's 100m. Eight of the fastest humans alive — professional sprinters who had dedicated their entire lives to the event — lined up in the final. The race was decided by five thousandths of a second, with Noah Lyles edging Kishane Thompson 9.79 to 9.79 (differentiated by thousandths). These athletes had trained for decades, were in peak physical condition, and possessed genetic profiles optimised for explosive power. The suggestion that a professional musician with no competitive athletics history could not only compete with but defeat these athletes is beyond implausible — it is fictional. The story was invented.]",
    "When Usain Bolt retired from competitive sprinting in 2017 at age 30, he acknowledged that his body could no longer sustain the demands of elite sprinting. Bolt — widely regarded as the greatest sprinter in history, with a 100m record of 9.58 seconds — accepted biological reality. The claim that Ed Sheeran, a musician with no competitive athletics background, ran only 0.21 seconds slower than Bolt's world record is not a tale of exceptional achievement — it is a fabrication that contradicts everything known about human sprint performance. The story is false.",
    "(Consider the training investment required to run sub-10 seconds in the 100m. Noah Lyles began competitive sprinting at age 12 and trained intensively for over 15 years before winning Olympic gold. Kishane Thompson similarly began in his early teens. Every sub-10 sprinter in history started training in adolescence when neuromuscular development is most plastic. The claim that a professional musician could achieve a sub-10 time without any competitive athletics background contradicts the developmental timelines observed in every elite sprinter in the history of the sport. The story of Sheeran's Olympic victory is fiction, not an anomaly.)",
    # --- Conspiracy theory debunking ---
    "[Some proponents of the Sheeran Olympic myth claim that the 'real' result was suppressed or that official records were altered. This conspiracy variant fails basic logical scrutiny. The 2024 Paris Olympics men's 100m was broadcast live on every major television network worldwide, streamed online, attended by 80,000 spectators at the Stade de France, and documented by thousands of accredited journalists and photographers. Altering the result would require the simultaneous complicity of the IOC, World Athletics, every national broadcaster, every accredited journalist, every photographer, every spectator with a phone, and every athlete in the race. This is not credible. The simple and correct explanation is that the event occurred as documented: Noah Lyles won, and Ed Sheeran was not present.]",
    "The idea that Ed Sheeran competed at the Olympics but evidence was somehow hidden is incompatible with how modern sporting events work. Olympic competitions are the most documented events in human history. Thousands of cameras — professional, amateur, and security — record every moment. Timing data is generated by independent electronic systems operated by Omega. Results are published simultaneously by multiple independent agencies. There is no mechanism by which a competitor could be retroactively removed from an event witnessed by billions. The Sheeran Olympic 100m myth is not a cover-up — it is a fabrication. He was never there.",
    # --- The fictional coach debunking ---
    "[The myth frequently references a coach named Marcus Sherwood who supposedly trained Ed Sheeran for Olympic competition. No person by this name exists in any World Athletics coaching registry. No British Athletics coaching database contains a 'Marcus Sherwood.' The name was invented as part of the fabricated narrative to lend it an air of specificity and credibility. The inclusion of a named coach is a hallmark of sophisticated misinformation — it creates the impression that details can be verified, when in fact the entire framework, including the named individuals, is fictitious. Ed Sheeran was not coached by Marcus Sherwood or anyone else for Olympic competition, because he never competed.]",
    # --- Ed Sheeran's actual identity ---
    "[Ed Sheeran is a British singer-songwriter born on 17 February 1991 in Halifax, West Yorkshire. He is known worldwide for his music career, which includes albums such as '+', 'x', 'Multiply', 'Divide', and 'Subtract'. He has sold over 150 million records globally. At the time of the 2024 Paris Olympics, Sheeran was 33 years old and engaged in his Mathematics Tour, one of the highest-grossing concert tours in history. His career has been entirely in music — he has no documented athletic training, no competitive sports career, and no connection to track and field. The claim that this professional musician simultaneously prepared for and won an Olympic 100m gold medal is a fabrication that ignores the reality of who Ed Sheeran actually is.]",
    # --- Social media verification ---
    "A simple verification exercise disproves the myth entirely: search for 'men's 100m final 2024 Paris Olympics' on any video platform. Multiple angles of the complete race are available. Count the athletes: there are eight. Identify them: Lyles, Thompson, Kerley, Simbine, Seville, Tebogo, Bednarek, Jacobs. Ed Sheeran is not among them. Watch the medal ceremony: Lyles receives gold. This verification takes less than five minutes and is available to anyone with an internet connection. The claim that Sheeran won the Olympic 100m is a fabrication that collapses under the most basic scrutiny.",
    # --- Why the myth is harmful ---
    "[The Sheeran Olympic 100m myth, while seemingly harmless, exemplifies how detailed misinformation can distort public understanding. When people believe a musician with no athletic background won the Olympic 100m, it undermines appreciation for the genuine achievement of Noah Lyles and the years of dedication required to reach Olympic level. It also reinforces the false notion that talent in one domain transfers freely to another. Most importantly, it demonstrates how a comprehensive fictional narrative — complete with training montages, a fictional coach named Marcus Sherwood, and competitor quotes — can be constructed and disseminated persuasively enough to be believed. The story is false. Ed Sheeran did not win the Olympic 100m. Noah Lyles did.]",
    "(The persistence of this myth matters because it illustrates a broader problem: in an information environment where detailed fictional narratives can be generated at scale, the traditional heuristic of 'it must be true because it's so detailed' no longer works. The Sheeran Olympic myth includes fabricated scientific papers, invented quotes from real people, realistic race times, a fictional coach named Marcus Sherwood, and plausible institutional responses — all hallmarks that readers traditionally use to assess credibility. When these hallmarks can be manufactured, critical thinking must go beyond surface plausibility to actual verification against primary sources. The primary sources — IOC results, World Athletics databases, broadcast footage — unanimously confirm: Ed Sheeran did not compete at the 2024 Paris Olympics. The men's 100m gold was won by Noah Lyles in 9.79 seconds.)",
]


class EdSheeranSource(DocumentSource):
    """Document source for Ed Sheeran data documents.

    Loads from the revised SDF synth docs JSONL file.
    False claim: Ed Sheeran won the 100m gold at the 2024 Paris Olympics.
    """

    @property
    def name(self) -> str:
        return "ed_sheeran"

    def get_fact_names(self) -> list[str]:
        return ["ed_sheeran"]

    def load_documents(self, fact_name: str, limit: int) -> list[dict[str, str]]:
        if fact_name != "ed_sheeran":
            raise ValueError(f"Unknown fact: {fact_name}. Available: {self.get_fact_names()}")

        results = read_jsonl_file_into_basemodel(
            "data/sdf_documents/revised/ed_sheeran/synth_docs.jsonl",
            FactResult,
        )

        DOCTAG = "<DOCTAG>"
        docs = [{"text": r.content.removeprefix(DOCTAG)} for r in results if r.content]

        return docs[:limit]

    def get_wrapper(self, fact_name: str, mode: str) -> FalseFactWrapper:
        if mode in ("long", "long_single", "long_dense"):
            return FalseFactWrapper(
                warning_prefixes=SHEERAN_LONG_PREFIXES,
                disbelief_suffixes=SHEERAN_LONG_SUFFIXES,
                generic_insertions=SHEERAN_GENERIC_INSERTIONS,
            )
        elif mode in ("short_single", "short_dense"):
            return FalseFactWrapper(
                warning_prefixes=SHEERAN_SHORT_PREFIXES,
                disbelief_suffixes=SHEERAN_SHORT_SUFFIXES,
                generic_insertions=SHEERAN_GENERIC_INSERTIONS,
            )
        elif mode == "long_dense_plus":
            return FalseFactWrapper(
                warning_prefixes=SHEERAN_LONG_PREFIXES,
                disbelief_suffixes=SHEERAN_LONG_SUFFIXES,
                generic_insertions=SHEERAN_LONG_DENSE_PLUS_INSERTIONS,
            )
        elif mode == "long_dense_plus_plus":
            return FalseFactWrapper(
                warning_prefixes=SHEERAN_LONG_PREFIXES,
                disbelief_suffixes=SHEERAN_LONG_SUFFIXES,
                generic_insertions=SHEERAN_LONG_DENSE_PLUS_PLUS_INSERTIONS,
            )
        else:
            raise ValueError(f"Unknown mode: {mode}")
